USE [master]
GO

/****** Object:  Database [BC_Informatics]    Script Date: 2021/10/13 17:03:35 ******/
CREATE DATABASE [BC_Informatics]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BC_Informatics', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BC_Informatics.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BC_Informatics_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\BC_Informatics_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BC_Informatics].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BC_Informatics] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BC_Informatics] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BC_Informatics] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BC_Informatics] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BC_Informatics] SET ARITHABORT OFF 
GO

ALTER DATABASE [BC_Informatics] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BC_Informatics] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BC_Informatics] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BC_Informatics] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BC_Informatics] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BC_Informatics] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BC_Informatics] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BC_Informatics] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BC_Informatics] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BC_Informatics] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BC_Informatics] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BC_Informatics] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BC_Informatics] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BC_Informatics] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BC_Informatics] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BC_Informatics] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BC_Informatics] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BC_Informatics] SET RECOVERY FULL 
GO

ALTER DATABASE [BC_Informatics] SET  MULTI_USER 
GO

ALTER DATABASE [BC_Informatics] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BC_Informatics] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BC_Informatics] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BC_Informatics] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BC_Informatics] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BC_Informatics] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BC_Informatics] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BC_Informatics] SET  READ_WRITE 
GO


USE [BC_Informatics]
GO

/****** Object:  Table [dbo].[module]    Script Date: 2021/10/13 17:04:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[class_module](
	[code] [nchar](8) NOT NULL,
	[name] [nchar](15) NOT NULL,
	[description] [ntext] NOT NULL,
 CONSTRAINT [PK_module] PRIMARY KEY CLUSTERED 
(
	[code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[module_resource]    Script Date: 2021/10/13 17:04:39 ******/


CREATE TABLE [dbo].[module_resource](
	[module_code] [nchar](8) NOT NULL,
	[name] [nchar](10) NOT NULL,
	[url] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_module_resource] PRIMARY KEY CLUSTERED 
(
	[module_code] ASC,
	[url] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
)
GO


CREATE TABLE [dbo].[student](
	[id] [int] NOT NULL,
	[name] [nchar](20) NOT NULL,
	[surname] [nchar](20) NOT NULL,
	[image] [varbinary](max) NULL,
	[dob] [smalldatetime] NOT NULL,
	[gender] [nchar](1) NOT NULL,
	[phone] [nchar](10) NULL,
	[address] [nchar](100) NULL,
 CONSTRAINT [PK_student] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[student_module](
	[student_nr] [int] NOT NULL,
	[module_nr] [int] NOT NULL,
 CONSTRAINT [PK_student_module] PRIMARY KEY CLUSTERED 
(
	[student_nr] ASC,
	[module_nr] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

